# Generated by Django 3.2.18 on 2023-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
