# Generated by Django 3.2.18 on 2023-03-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('booking', '0002_booking_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='table_number',
            field=models.ManyToManyField(related_name='booked_table', to='location.Table'),
        ),
    ]
